sudo apt install libnss3
sudo apt-get install libatk1.0-0
sudo apt-get install libatk-bridge2.0-0
sudo apt-get install libx11-xcb1
sudo apt-get install libxcb-dri3-0
sudo apt-get install libxcomposite1 
sudo apt-get install libxdamage1
sudo apt-get install libxfixes3
sudo apt-get install libcups2
sudo apt-get install libdrm2
sudo apt-get install libxrandr2
sudo apt-get install libgbm1
sudo apt-get install libasound2
sudo apt-get install libpangocairo-1.0-0
sudo apt-get install libgtk-3-0